version: '3.8'

services:
  db:
    image: ikbs-postgres:latest
    restart: always
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ikbs
    command: ["postgres", "-c", "listen_addresses=*"]
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
